services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped